# Generated by Django 2.2.7 on 2019-11-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='songs',
            new_name='playlist_songs',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='song_artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='song_title',
        ),
    ]
