# Generated by Django 2.2.7 on 2019-11-28 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191128_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Playlist')),
            ],
        ),
    ]
